"""Add image column to Product

Revision ID: 6b6db8948d2c
Revises: 
Create Date: 2024-07-14 15:49:36.633698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6db8948d2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(length=255),
               existing_nullable=True)
    op.alter_column('product', 'price',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'product', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.alter_column('product', 'price',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('product', 'title',
               existing_type=sa.Text(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
